CREATE DATABASE COLLEGE;

USE COLLEGE;

CREATE TABLE STUDENT(
ID INT PRIMARY KEY,
NAME VARCHAR(20),
AGE INT NOT NULL
);

INSERT INTO STUDENT VALUES(1,"SHUBHAM",16);
INSERT INTO STUDENT VALUES(2,"POOJA",24);

SELECT *FROM STUDENT;
