CREATE DATABASE IF NOT EXISTS XYZ;

USE XYZ;

CREATE TABLE EMPLOYEE(
ID INT PRIMARY KEY,
NAME VARCHAR(40),
SALARY INT NOT NULL
);

INSERT INTO EMPLOYEE VALUES(1,"ADAM",25000);
INSERT INTO EMPLOYEE VALUES(2,"BOB",30000);
INSERT INTO EMPLOYEE VALUES(3,"CASEY",40000);

SELECT * FROM EMPLOYEE;

